//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunarCalendar.MobileApp.Resources.Strings {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LunarCalendar.MobileApp.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }

        public static string WelcomeTagline {
            get {
                return ResourceManager.GetString("WelcomeTagline", resourceCulture);
            }
        }

        public static string ContinueAsGuest {
            get {
                return ResourceManager.GetString("ContinueAsGuest", resourceCulture);
            }
        }

        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }

        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }

        public static string GuestModeInfo {
            get {
                return ResourceManager.GetString("GuestModeInfo", resourceCulture);
            }
        }

        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }

        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }

        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        public static string DisplaySettings {
            get {
                return ResourceManager.GetString("DisplaySettings", resourceCulture);
            }
        }

        public static string CulturalBackground {
            get {
                return ResourceManager.GetString("CulturalBackground", resourceCulture);
            }
        }

        public static string CulturalBackgroundDesc {
            get {
                return ResourceManager.GetString("CulturalBackgroundDesc", resourceCulture);
            }
        }

        public static string ShowLunarDates {
            get {
                return ResourceManager.GetString("ShowLunarDates", resourceCulture);
            }
        }

        public static string ShowLunarDatesDesc {
            get {
                return ResourceManager.GetString("ShowLunarDatesDesc", resourceCulture);
            }
        }

        public static string UpcomingHolidaysRange {
            get {
                return ResourceManager.GetString("UpcomingHolidaysRange", resourceCulture);
            }
        }

        public static string UpcomingHolidaysRangeDesc {
            get {
                return ResourceManager.GetString("UpcomingHolidaysRangeDesc", resourceCulture);
            }
        }

        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }

        public static string LanguageDesc {
            get {
                return ResourceManager.GetString("LanguageDesc", resourceCulture);
            }
        }

        public static string InteractionSettings {
            get {
                return ResourceManager.GetString("InteractionSettings", resourceCulture);
            }
        }

        public static string HapticFeedback {
            get {
                return ResourceManager.GetString("HapticFeedback", resourceCulture);
            }
        }

        public static string HapticFeedbackDesc {
            get {
                return ResourceManager.GetString("HapticFeedbackDesc", resourceCulture);
            }
        }

        public static string SyncAndOffline {
            get {
                return ResourceManager.GetString("SyncAndOffline", resourceCulture);
            }
        }

        public static string ConnectionStatus {
            get {
                return ResourceManager.GetString("ConnectionStatus", resourceCulture);
            }
        }

        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }

        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }

        public static string LastSync {
            get {
                return ResourceManager.GetString("LastSync", resourceCulture);
            }
        }

        public static string SyncNow {
            get {
                return ResourceManager.GetString("SyncNow", resourceCulture);
            }
        }

        public static string Syncing {
            get {
                return ResourceManager.GetString("Syncing", resourceCulture);
            }
        }

        public static string DataAndStorage {
            get {
                return ResourceManager.GetString("DataAndStorage", resourceCulture);
            }
        }

        public static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }

        public static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }

        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }

        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }

        public static string AboutThisApp {
            get {
                return ResourceManager.GetString("AboutThisApp", resourceCulture);
            }
        }

        public static string SyncComplete {
            get {
                return ResourceManager.GetString("SyncComplete", resourceCulture);
            }
        }

        public static string SyncCompleteMessage {
            get {
                return ResourceManager.GetString("SyncCompleteMessage", resourceCulture);
            }
        }

        public static string SyncFailed {
            get {
                return ResourceManager.GetString("SyncFailed", resourceCulture);
            }
        }

        public static string SyncFailedMessage {
            get {
                return ResourceManager.GetString("SyncFailedMessage", resourceCulture);
            }
        }

        public static string SyncError {
            get {
                return ResourceManager.GetString("SyncError", resourceCulture);
            }
        }

        public static string SyncErrorMessage {
            get {
                return ResourceManager.GetString("SyncErrorMessage", resourceCulture);
            }
        }

        public static string OfflineMessage {
            get {
                return ResourceManager.GetString("OfflineMessage", resourceCulture);
            }
        }

        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }

        public static string SyncServiceNotAvailable {
            get {
                return ResourceManager.GetString("SyncServiceNotAvailable", resourceCulture);
            }
        }

        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }

        public static string CacheClearedMessage {
            get {
                return ResourceManager.GetString("CacheClearedMessage", resourceCulture);
            }
        }

        public static string ClearCacheError {
            get {
                return ResourceManager.GetString("ClearCacheError", resourceCulture);
            }
        }

        public static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }

        public static string ResetSettingsTitle {
            get {
                return ResourceManager.GetString("ResetSettingsTitle", resourceCulture);
            }
        }

        public static string ResetSettingsMessage {
            get {
                return ResourceManager.GetString("ResetSettingsMessage", resourceCulture);
            }
        }

        public static string SettingsResetMessage {
            get {
                return ResourceManager.GetString("SettingsResetMessage", resourceCulture);
            }
        }

        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }

        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        public static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }

        public static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }

        public static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }

        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }

        public static string VietnameseHolidays {
            get {
                return ResourceManager.GetString("VietnameseHolidays", resourceCulture);
            }
        }

        public static string GregorianDate {
            get {
                return ResourceManager.GetString("GregorianDate", resourceCulture);
            }
        }

        public static string LunarDate {
            get {
                return ResourceManager.GetString("LunarDate", resourceCulture);
            }
        }

        public static string PublicHoliday {
            get {
                return ResourceManager.GetString("PublicHoliday", resourceCulture);
            }
        }

        public static string CultureLabel {
            get {
                return ResourceManager.GetString("Culture", resourceCulture);
            }
        }

        public static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }

        public static string RestartRequiredMessage {
            get {
                return ResourceManager.GetString("RestartRequiredMessage", resourceCulture);
            }
        }

        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }

        public static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }

        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }

        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }

        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }

        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }

        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }

        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }

        public static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }

        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }

        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }

        public static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }

        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }

        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }

        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }

        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }

        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }

        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }

        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }

        public static string UpcomingHolidaysTitle {
            get {
                return ResourceManager.GetString("UpcomingHolidaysTitle", resourceCulture);
            }
        }

        public static string NoUpcomingHolidays {
            get {
                return ResourceManager.GetString("NoUpcomingHolidays", resourceCulture);
            }
        }

        public static string AboutThisHoliday {
            get {
                return ResourceManager.GetString("AboutThisHoliday", resourceCulture);
            }
        }

        public static string TodayLabel {
            get {
                return ResourceManager.GetString("TodayLabel", resourceCulture);
            }
        }

        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }

        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }

        public static string UpcomingHolidaysFormat {
            get {
                return ResourceManager.GetString("UpcomingHolidaysFormat", resourceCulture);
            }
        }

        public static string NoUpcomingHolidaysMessage {
            get {
                return ResourceManager.GetString("NoUpcomingHolidaysMessage", resourceCulture);
            }
        }

        public static string LunarLabel {
            get {
                return ResourceManager.GetString("LunarLabel", resourceCulture);
            }
        }

        public static string YearOfThe {
            get {
                return ResourceManager.GetString("YearOfThe", resourceCulture);
            }
        }

        public static string AnimalRat {
            get {
                return ResourceManager.GetString("AnimalRat", resourceCulture);
            }
        }

        public static string AnimalOx {
            get {
                return ResourceManager.GetString("AnimalOx", resourceCulture);
            }
        }

        public static string AnimalTiger {
            get {
                return ResourceManager.GetString("AnimalTiger", resourceCulture);
            }
        }

        public static string AnimalRabbit {
            get {
                return ResourceManager.GetString("AnimalRabbit", resourceCulture);
            }
        }

        public static string AnimalDragon {
            get {
                return ResourceManager.GetString("AnimalDragon", resourceCulture);
            }
        }

        public static string AnimalSnake {
            get {
                return ResourceManager.GetString("AnimalSnake", resourceCulture);
            }
        }

        public static string AnimalHorse {
            get {
                return ResourceManager.GetString("AnimalHorse", resourceCulture);
            }
        }

        public static string AnimalGoat {
            get {
                return ResourceManager.GetString("AnimalGoat", resourceCulture);
            }
        }

        public static string AnimalMonkey {
            get {
                return ResourceManager.GetString("AnimalMonkey", resourceCulture);
            }
        }

        public static string AnimalRooster {
            get {
                return ResourceManager.GetString("AnimalRooster", resourceCulture);
            }
        }

        public static string AnimalDog {
            get {
                return ResourceManager.GetString("AnimalDog", resourceCulture);
            }
        }

        public static string AnimalPig {
            get {
                return ResourceManager.GetString("AnimalPig", resourceCulture);
            }
        }

        public static string MajorDay {
            get {
                return ResourceManager.GetString("MajorDay", resourceCulture);
            }
        }

        public static string TraditionalFestival {
            get {
                return ResourceManager.GetString("TraditionalFestival", resourceCulture);
            }
        }

        public static string SeasonalCelebration {
            get {
                return ResourceManager.GetString("SeasonalCelebration", resourceCulture);
            }
        }

        public static string LunarSpecialDay {
            get {
                return ResourceManager.GetString("LunarSpecialDay", resourceCulture);
            }
        }

        public static string LunarSpecialDay_FirstDay_Name {
            get {
                return ResourceManager.GetString("LunarSpecialDay_FirstDay_Name", resourceCulture);
            }
        }

        public static string LunarSpecialDay_FirstDay_Description {
            get {
                return ResourceManager.GetString("LunarSpecialDay_FirstDay_Description", resourceCulture);
            }
        }

        public static string LunarSpecialDay_FullMoon_Name {
            get {
                return ResourceManager.GetString("LunarSpecialDay_FullMoon_Name", resourceCulture);
            }
        }

        public static string LunarSpecialDay_FullMoon_Description {
            get {
                return ResourceManager.GetString("LunarSpecialDay_FullMoon_Description", resourceCulture);
            }
        }

        // Holiday Names
        public static string Holiday_TetNguyenDan1_Name {
            get {
                return ResourceManager.GetString("Holiday_TetNguyenDan1_Name", resourceCulture);
            }
        }

        public static string Holiday_TetNguyenDan2_Name {
            get {
                return ResourceManager.GetString("Holiday_TetNguyenDan2_Name", resourceCulture);
            }
        }

        public static string Holiday_TetNguyenDan3_Name {
            get {
                return ResourceManager.GetString("Holiday_TetNguyenDan3_Name", resourceCulture);
            }
        }

        public static string Holiday_HungKings_Name {
            get {
                return ResourceManager.GetString("Holiday_HungKings_Name", resourceCulture);
            }
        }

        public static string Holiday_NewYear_Name {
            get {
                return ResourceManager.GetString("Holiday_NewYear_Name", resourceCulture);
            }
        }

        public static string Holiday_ReunificationDay_Name {
            get {
                return ResourceManager.GetString("Holiday_ReunificationDay_Name", resourceCulture);
            }
        }

        public static string Holiday_LaborDay_Name {
            get {
                return ResourceManager.GetString("Holiday_LaborDay_Name", resourceCulture);
            }
        }

        public static string Holiday_NationalDay_Name {
            get {
                return ResourceManager.GetString("Holiday_NationalDay_Name", resourceCulture);
            }
        }

        public static string Holiday_LanternFestival_Name {
            get {
                return ResourceManager.GetString("Holiday_LanternFestival_Name", resourceCulture);
            }
        }

        public static string Holiday_ColdFood_Name {
            get {
                return ResourceManager.GetString("Holiday_ColdFood_Name", resourceCulture);
            }
        }

        public static string Holiday_DragonBoat_Name {
            get {
                return ResourceManager.GetString("Holiday_DragonBoat_Name", resourceCulture);
            }
        }

        public static string Holiday_Ullambana_Name {
            get {
                return ResourceManager.GetString("Holiday_Ullambana_Name", resourceCulture);
            }
        }

        public static string Holiday_MidAutumn_Name {
            get {
                return ResourceManager.GetString("Holiday_MidAutumn_Name", resourceCulture);
            }
        }

        public static string Holiday_DoubleNinth_Name {
            get {
                return ResourceManager.GetString("Holiday_DoubleNinth_Name", resourceCulture);
            }
        }

        public static string Holiday_FirstFullMoon_Name {
            get {
                return ResourceManager.GetString("Holiday_FirstFullMoon_Name", resourceCulture);
            }
        }

        public static string Holiday_TombSweeping_Name {
            get {
                return ResourceManager.GetString("Holiday_TombSweeping_Name", resourceCulture);
            }
        }

        public static string Holiday_GhostFestival_Name {
            get {
                return ResourceManager.GetString("Holiday_GhostFestival_Name", resourceCulture);
            }
        }

        public static string Holiday_KitchenGods_Name {
            get {
                return ResourceManager.GetString("Holiday_KitchenGods_Name", resourceCulture);
            }
        }

        public static string Holiday_NewYearsEve_Name {
            get {
                return ResourceManager.GetString("Holiday_NewYearsEve_Name", resourceCulture);
            }
        }

        // Holiday Descriptions
        public static string Holiday_TetNguyenDan1_Description {
            get {
                return ResourceManager.GetString("Holiday_TetNguyenDan1_Description", resourceCulture);
            }
        }

        public static string Holiday_TetNguyenDan2_Description {
            get {
                return ResourceManager.GetString("Holiday_TetNguyenDan2_Description", resourceCulture);
            }
        }

        public static string Holiday_TetNguyenDan3_Description {
            get {
                return ResourceManager.GetString("Holiday_TetNguyenDan3_Description", resourceCulture);
            }
        }

        public static string Holiday_HungKings_Description {
            get {
                return ResourceManager.GetString("Holiday_HungKings_Description", resourceCulture);
            }
        }

        public static string Holiday_NewYear_Description {
            get {
                return ResourceManager.GetString("Holiday_NewYear_Description", resourceCulture);
            }
        }

        public static string Holiday_ReunificationDay_Description {
            get {
                return ResourceManager.GetString("Holiday_ReunificationDay_Description", resourceCulture);
            }
        }

        public static string Holiday_LaborDay_Description {
            get {
                return ResourceManager.GetString("Holiday_LaborDay_Description", resourceCulture);
            }
        }

        public static string Holiday_NationalDay_Description {
            get {
                return ResourceManager.GetString("Holiday_NationalDay_Description", resourceCulture);
            }
        }

        public static string Holiday_LanternFestival_Description {
            get {
                return ResourceManager.GetString("Holiday_LanternFestival_Description", resourceCulture);
            }
        }

        public static string Holiday_ColdFood_Description {
            get {
                return ResourceManager.GetString("Holiday_ColdFood_Description", resourceCulture);
            }
        }

        public static string Holiday_DragonBoat_Description {
            get {
                return ResourceManager.GetString("Holiday_DragonBoat_Description", resourceCulture);
            }
        }

        public static string Holiday_Ullambana_Description {
            get {
                return ResourceManager.GetString("Holiday_Ullambana_Description", resourceCulture);
            }
        }

        public static string Holiday_MidAutumn_Description {
            get {
                return ResourceManager.GetString("Holiday_MidAutumn_Description", resourceCulture);
            }
        }

        public static string Holiday_DoubleNinth_Description {
            get {
                return ResourceManager.GetString("Holiday_DoubleNinth_Description", resourceCulture);
            }
        }

        public static string Holiday_FirstFullMoon_Description {
            get {
                return ResourceManager.GetString("Holiday_FirstFullMoon_Description", resourceCulture);
            }
        }

        public static string Holiday_TombSweeping_Description {
            get {
                return ResourceManager.GetString("Holiday_TombSweeping_Description", resourceCulture);
            }
        }

        public static string Holiday_GhostFestival_Description {
            get {
                return ResourceManager.GetString("Holiday_GhostFestival_Description", resourceCulture);
            }
        }

        public static string Holiday_KitchenGods_Description {
            get {
                return ResourceManager.GetString("Holiday_KitchenGods_Description", resourceCulture);
            }
        }

        public static string Holiday_NewYearsEve_Description {
            get {
                return ResourceManager.GetString("Holiday_NewYearsEve_Description", resourceCulture);
            }
        }

        public static string SelectMonthYear {
            get {
                return ResourceManager.GetString("SelectMonthYear", resourceCulture);
            }
        }

        public static string SelectMonth {
            get {
                return ResourceManager.GetString("SelectMonth", resourceCulture);
            }
        }

        public static string SelectYear {
            get {
                return ResourceManager.GetString("SelectYear", resourceCulture);
            }
        }

        public static string GoToToday {
            get {
                return ResourceManager.GetString("GoToToday", resourceCulture);
            }
        }
    }
}
