#!/bin/bash
# Filter Console logs for LunarCalendar app only

echo "📱 Filtering logs for LunarCalendar app"
echo "========================================"
echo ""
echo "In Console.app, please:"
echo "1. Clear the log display (Edit → Clear Display)"
echo "2. Make sure you're filtering for your iPhone"
echo "3. In the search box at the top, enter:"
echo ""
echo "   process:\"LunarCalendar\" OR subsystem:\"com.huynguyen.lunarcalendar\""
echo ""
echo "4. Launch the app on your iPhone"
echo "5. Look for messages containing:"
echo "   - 'CRASH'"
echo "   - 'Exception'"
echo "   - 'terminated'"
echo "   - Lines from our Debug.WriteLine statements"
echo ""
echo "You should see messages like:"
echo "   === AppDelegate: FinishedLaunching START ==="
echo "   === Initializing SQLite ==="
echo "   === App Constructor START ==="
echo ""
echo "If you see NONE of these messages, the app is crashing"
echo "BEFORE our code even runs (likely a framework issue)."
echo ""
echo "Press Enter when ready to see alternative diagnostics..."
read

echo ""
echo "Alternative: Check crash reports in Settings"
echo "============================================="
echo ""
echo "On your iPhone:"
echo "1. Settings → Privacy & Security → Analytics & Improvements"
echo "2. Analytics Data"
echo "3. Look for any 'LunarCalendar' entries"
echo "4. Tap to view the crash report"
echo "5. Take a screenshot or note the Exception Type"
echo ""
